# docker run -d --rm --name mongo -p 27017:27017 -v mondodbdata:/data/db mongo

version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mondodbdata:/data/db

volumes:
  mondodbdata:
